# Swagger API文档（是否开启）
swagger:
  enable: false

redirect:
  url: https://jsbceshi.hfi-health.com:18188/e-contract/

file:
  path: /jingt/医保定点机构列表20210607.xlsx
  pathCsv: /jingt/医保定点机构列表20210607.csv
  down:
    url: /jingt
#天印系统接口配置
esignpro:
  url:  http://172.16.80.191:8088
  projectId: 1001001
  secret: c5505d7831bc626e92c175052956c7fc


mybatis-plus:
  mapper-locations: classpath*:com/hfi/insurance/mapper/**/*.xml