# Swagger API文档（是否开启）
swagger:
  enable: true

file:
  path: C:\Users\hengtian\Desktop\医保定点机构列表20210607.xlsx
  pathCsv: C:\Users\hengtian\Desktop\医保定点机构列表20210607.csv
  down:
    url: E:\demo
#天印系统接口配置
esignpro:
  url: http://172.16.80.191:8088
  projectId: 1001001
  secret: c5505d7831bc626e92c175052956c7fc