# Swagger API文档（是否开启）
swagger:
  enable: true

redirect:
  url: http://192.20.97.35:18080/e-contract/#
  ybUrl: http://172.16.29.54:18080/e-contract/#

file:
  path: C:\Users\hengtian\Desktop\医保定点机构列表20210607.xlsx
  pathCsv: C:\Users\hengtian\Desktop\医保定点机构列表20210607.csv
  down:
    url: E:\demo
  pic:
    uploadPathImg: E:\Temp\img
#天印系统接口配置
esignpro:
  urls: http://172.16.29.54:8088
  url: http://172.16.80.191:8088
  projectId: 1001001
  secret: c5505d7831bc626e92c175052956c7fc
spring:
  datasource:
    username: test
    password: test@22
    url: jdbc:mysql://192.30.255.22:3306/db_insurance_info?useUnicode\=true&characterEncoding\=utf-8&allowMultiQueries\=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 10000
      #允许连接在连接池中空闲的最长时间(以毫秒为单位)
      idle-timeout: 30000
      #连接将被测试活动的最大时间量
      validation-timeout: 3000
      #池中连接关闭后的最长生命周期
      max-lifetime: 30000
      #最大池大小
      maximum-pool-size:  60
      #连接池中维护的最小空闲连接数
      minimum-idle: 10
      #从池返回的连接的默认自动提交行为。默认值为true
      auto-commit: true
      #如果您的驱动程序支持JDBC4，我们强烈建议您不要设置此属性
      connection-test-query: SELECT 1
  #  datasource:
  #    username: root
  #    password: Zaq1@3edc
  #    jdbc-url: jdbc:mysql://122.51.48.108:3306/eass?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    mapper-locations: classpath*:com/hfi/insurance/mapper/**/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
logging:
  application-name: insurance-info-server
  dir: logs
  level:
    com:
      hfi:
        insurance: debug
#  file:
#    path: logs

mybatis-plus:
  mapper-locations: classpath*:com/hfi/insurance/mapper/**/*.xml

############# upload file
uploadFile:
  path: https://jsbceshi.hfi-health.com:18188/appsImg/
  dir: /home/imgTestZmz
  userName: imgTestZmz
  password: img123_hfi_health
  host: 192.20.97.35
  port: 21

sign:
  callBack:
    url: http://localhost:8090/insurance_info/callBack/flowStatusNotify