server:
  port: 8097
# Swagger API文档（是否开启）
swagger:
  enable: true

redirect:
  url: ../e-contract/
  ybUrl: ../e-contract/

file:
  path: /opt/app/insurance-info-server/service/医保定点机构列表20210607.xlsx
  pathCsv: /opt/app/insurance-info-server/service/医保定点机构列表20210607.csv
  down:
    url: /opt/app/insurance-info-server/service/demo
  pic:
    uploadPathImg: /opt/app/insurance-info-server/pic
#天印系统接口配置
esignpro:
  url: http://192.50.10.43:8088
  projectId: 1001001
  secret: ac1bffd524b2b42cee6929d58c77b8d1

spring:
  datasource:
    username: user_insurance_info
    password: caTKaqT9zw
    url: jdbc:mysql://192.50.50.31:3306/db_insurance_info?useUnicode\=true&characterEncoding\=utf-8&allowMultiQueries\=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 10000
      #允许连接在连接池中空闲的最长时间(以毫秒为单位)
      idle-timeout: 30000
      #连接将被测试活动的最大时间量
      validation-timeout: 3000
      #池中连接关闭后的最长生命周期
      max-lifetime: 30000
      #最大池大小
      maximum-pool-size:  60
      #连接池中维护的最小空闲连接数
      minimum-idle: 10
      #从池返回的连接的默认自动提交行为。默认值为true
      auto-commit: true
      #如果您的驱动程序支持JDBC4，我们强烈建议您不要设置此属性
      connection-test-query: SELECT 1
  #  datasource:
  #    username: root
  #    password: Zaq1@3edc
  #    jdbc-url: jdbc:mysql://122.51.48.108:3306/eass?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
  #    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  application-name: insurance-info-server
  dir: opt/app/insurance-info-server/logs
  level:
    com:
      hfi:
        insurance: debug
#  file:
#    path: logs

mybatis-plus:
  mapper-locations: classpath*:com/hfi/insurance/mapper/**/*.xml